// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALeG_M2uefV4uojV3qm2Ugka4pAX_tqkI',
    appId: '1:414345647241:web:70ff7c210f11fb28ff2258',
    messagingSenderId: '414345647241',
    projectId: 'logintodo-58665',
    authDomain: 'logintodo-58665.firebaseapp.com',
    storageBucket: 'logintodo-58665.firebasestorage.app',
    measurementId: 'G-DFEML6637V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmWGfHmbIv0nib4zO8LIrrRt7QRWyxVdI',
    appId: '1:414345647241:android:777b7640d22def6bff2258',
    messagingSenderId: '414345647241',
    projectId: 'logintodo-58665',
    storageBucket: 'logintodo-58665.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYmoywmolTS0Qxm0MvnuYXXepgqNvFnU4',
    appId: '1:414345647241:ios:a6cb74d41ed9da41ff2258',
    messagingSenderId: '414345647241',
    projectId: 'logintodo-58665',
    storageBucket: 'logintodo-58665.firebasestorage.app',
    iosBundleId: 'com.example.loginTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYmoywmolTS0Qxm0MvnuYXXepgqNvFnU4',
    appId: '1:414345647241:ios:a6cb74d41ed9da41ff2258',
    messagingSenderId: '414345647241',
    projectId: 'logintodo-58665',
    storageBucket: 'logintodo-58665.firebasestorage.app',
    iosBundleId: 'com.example.loginTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALeG_M2uefV4uojV3qm2Ugka4pAX_tqkI',
    appId: '1:414345647241:web:0a422eedac66e2dcff2258',
    messagingSenderId: '414345647241',
    projectId: 'logintodo-58665',
    authDomain: 'logintodo-58665.firebaseapp.com',
    storageBucket: 'logintodo-58665.firebasestorage.app',
    measurementId: 'G-WFMPJ6CCTT',
  );
}
